Standard_L8s="Standard_L8s"
Standard_L16s_v2="Standard_L16s_v2"
Standard_L16s="Standard_L16s"
Standard_L4s="Standard_L4s"
Standard_DS3_v2="Standard_DS3_v2"
cmr_cmr_host_var=""
cmr_cmr_token_var=""
cmr_cmr_workspace_id_var=""
