export TF_VAR_Standard_L8s="Standard_L8s"
export TF_VAR_Standard_L16s_v2="Standard_L16s_v2"
export TF_VAR_Standard_L16s="Standard_L16s"
export TF_VAR_Standard_L4s="Standard_L4s"
export TF_VAR_Standard_DS3_v2="Standard_DS3_v2"
export TF_VAR_cmr_cmr_host_var=""
export TF_VAR_cmr_cmr_token_var=""
export TF_VAR_cmr_cmr_workspace_id_var=""
